@baseUrl = http://127.0.0.1:3000/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2YmQ4MTUxMC04YTA4LTRiNTAtYmNmNS1iODRmNGE4N2U4NmIiLCJzY29wZSI6WyJFbXBsb3llZSJdLCJpYXQiOjE2NjIxOTE4NDd9.x8hZEgVPAO284_d-SqeAy5hgfq9Iuk-Gr60SyuF5fXo
###
POST {{baseUrl}}/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "phone": "110-110-110",
    "email": "janedoe@test.com",
    "password": "test@test",
    "gender": "Female",
    "roles": ["Employee"]
}

###
GET {{baseUrl}}/users/me
Authorization: {{token}}

### 
GET {{baseUrl}}/users
Authorization: {{token}}