@baseUrl = http://localhost:3000/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2YmQ4MTUxMC04YTA4LTRiNTAtYmNmNS1iODRmNGE4N2U4NmIiLCJzY29wZSI6WyJFbXBsb3llZSJdLCJpYXQiOjE2NjIxOTE4NDd9.x8hZEgVPAO284_d-SqeAy5hgfq9Iuk-Gr60SyuF5fXo

###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "janedoe@test.com",
    "password": "test@test"
}

###
GET {{baseUrl}}/auth
Authorization: {{token}}