@baseUrl = http://localhost:3000/api
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI0ZmE5YzMwZS0wZjFlLTRjZDctYjNjYi00YWQxYmYxNWVlNTgiLCJzY29wZSI6WyJFbXBsb3llZSJdLCJpYXQiOjE2NjM0MDYzNDl9.hus6mVYTTKyA2rGuKIWJxfKd5aPL2X_lKJi-h3bT3TI

###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "janedoe@test.com",
    "password": "test@test"
}

###
GET {{baseUrl}}/auth
Authorization: {{token}}